### PR TITLE
Bring Legato project up to date with latest Data Hub

### PR DESCRIPTION
**Pull request by jtchitty**
These are all non-breaking changes.  That is, all existing clients should continue to work after a re-build.
- The resource naming conventions in the io.api were out of date wrt what people are actually doing. Updated that.
- psensor component was using malloc() and free(). Converted to a memory pool.
- Added a psensor_CreateJSON() that takes a JSON example string instead of a data type, but otherwise functions in exactly the same way as the generic psensor_Create() function.
- Made it possible to have all the resources of a periodic sensor appear directly under the app name in the data hub.
- Trigger a first sample immediately upon enabling when a period is configured, rather than waiting until the first timer expiry before triggering the first sample.
- Moved the observation buffer backup directory on embedded targets from /data to /home/root to make this feature work again on newer Sierra Wireless WP modules.
- Added a second pool for smaller string data samples so we don't have to allocate 50KB for every little string.

### CODE REVIEW

**Review by dpfrey — CHANGES_REQUESTED** [review]
It seems that the merge commit (e893575) serves no purpose.  This can be verified by observing that `git diff d5f1b5b..e893575` is empty.  You can eliminate the unnecessary merge commit by doing: `git checkout -b pr_fixup d5f1b5b && git cherry-pick e3a8730 f71dc9b` to create a new branch that contains your two commits without the merge commit.  Once you are satisfied that the content of the new branch is the same as the branch you made the pull request from (master), you can do: `git checkout -B master && git branch -D pr_fixup && git push --force-with-lease origin master`.  By pushing to the branch that you made the pull request from, the pull request will automatically be updated.

Also, FYI: It's typical to create a descriptively named branch when making a pull request.  By making your pull request from the master branch of your repository, it means that you can't push additional development to the master branch of your repository without it showing up in this pull request.

**Comment by jtchitty** [comment]
> It seems that the merge commit (e893575) serves no purpose. This can be verified by observing that git diff d5f1b5b..e893575 is empty. You can eliminate the unnecessary merge commit by doing: git checkout -b pr_fixup d5f1b5b && git cherry-pick e3a8730 f71dc9b to create a new branch that contains your two commits without the merge commit. Once you are satisfied that the content of the new branch is the same as the branch you made the pull request from (master), you can do: git checkout -B master && git branch -D pr_fixup && git push --force-with-lease origin master. By pushing to the branch that you made the pull request from, the pull request will automatically be updated.

This merge commit was created by GitHub when it merged my pull request containing the changes from legatoproject.  I'm not going to waste my time cleaning that out of the commit history.

> Also, FYI: It's typical to create a descriptively named branch when making a pull request. By making your pull request from the master branch of your repository, it means that you can't push additional development to the master branch of your repository without it showing up in this pull request.

Good point.  I'll do that next time.

**Comment by jtchitty** [comment]
> Why not?
> `return strnlen(string, SMALL_STRING_BYTES) < SMALL_STRING_BYTES;`

Hmm...  I knew there was a strnlen(), but I must have misspelled it when I typed `man strnlen()`, and for some reason it's not included in the list of string functions in `man string`.  I'll update that.

**Comment by jtchitty** [comment]
> `#define SMALL_STRING_SAMPLE_OBJECT_BYTES (sizeof(DataSample_t) + SMALL_STRING_BYTES - sizeof(double))`
> could be rewritten as:
> `#define SMALL_STRING_SAMPLE_OBJECT_BYTES (offsetof(DataSample_t, value) + SMALL_STRING_BYTES)`
> 
> This is better because it doesn't make the reader wonder "why sizeof(double)?" and it will continue to function correctly if a member larger than a `double` is added to the `value` union.

Good idea.

**Pull request merged**
